[2025-08-19T04:18:49.136+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-19T04:18:49.163+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: multi_scripts_every_5min.run_script1 scheduled__2025-08-19T04:10:00+00:00 [queued]>
[2025-08-19T04:18:49.178+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: multi_scripts_every_5min.run_script1 scheduled__2025-08-19T04:10:00+00:00 [queued]>
[2025-08-19T04:18:49.180+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-08-19T04:18:49.204+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_script1> on 2025-08-19 04:10:00+00:00
[2025-08-19T04:18:49.215+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=201) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-19T04:18:49.218+0000] {standard_task_runner.py:72} INFO - Started process 204 to run task
[2025-08-19T04:18:49.216+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'multi_scripts_every_5min', 'run_script1', 'scheduled__2025-08-19T04:10:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8a61akvu']
[2025-08-19T04:18:49.220+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_script1
[2025-08-19T04:18:49.296+0000] {task_command.py:467} INFO - Running <TaskInstance: multi_scripts_every_5min.run_script1 scheduled__2025-08-19T04:10:00+00:00 [running]> on host 6ff8e1de8f0e
[2025-08-19T04:18:49.419+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='multi_scripts_every_5min' AIRFLOW_CTX_TASK_ID='run_script1' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T04:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T04:10:00+00:00'
[2025-08-19T04:18:49.420+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-19T04:18:49.529+0000] {logging_mixin.py:190} INFO - === STDOUT (/opt/***/scripts/test_db.py) ===
[2025-08-19T04:18:49.530+0000] {logging_mixin.py:190} INFO - === STDERR (/opt/***/scripts/test_db.py) ===
Traceback (most recent call last):
  File "/opt/***/scripts/test_db.py", line 1, in <module>
    from data_quality_monitoring.data_bases.extract_data import execute
ModuleNotFoundError: No module named 'data_quality_monitoring'
[2025-08-19T04:18:49.530+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 15, in run_script
    result.check_returncode()  # lève une erreur si exit code != 0
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/scripts/test_db.py']' returned non-zero exit status 1.
[2025-08-19T04:18:49.552+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=multi_scripts_every_5min, task_id=run_script1, run_id=scheduled__2025-08-19T04:10:00+00:00, execution_date=20250819T041000, start_date=20250819T041849, end_date=20250819T041849
[2025-08-19T04:18:49.569+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-19T04:18:49.570+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task run_script1 (Command '['python', '/opt/airflow/scripts/test_db.py']' returned non-zero exit status 1.; 204)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 15, in run_script
    result.check_returncode()  # lève une erreur si exit code != 0
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/scripts/test_db.py']' returned non-zero exit status 1.
[2025-08-19T04:18:49.596+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-19T04:18:49.619+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T04:18:49.623+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
